import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  users: defineTable({
    displayName: v.string(),
    username: v.string(),
    email: v.optional(v.string()),
    role: v.string(),
    serviceGroups: v.optional(v.array(v.string())),
    approvalScopes: v.optional(v.array(v.string())),
    department: v.optional(v.string()),
    section: v.optional(v.string()),
    active: v.boolean(),
    passwordHash: v.optional(v.string()),
    passwordUpdatedAt: v.optional(v.number()),
    createdAt: v.number(),
    updatedAt: v.number(),
    createdBy: v.optional(v.string()),
  })
    .index("by_username", ["username"])
    .index("by_role", ["role"])
    .index("by_active", ["active"]),
  departments: defineTable({
    name: v.string(),
    active: v.boolean(),
    createdAt: v.number(),
  }).index("by_active", ["active"]),
  assets: defineTable({
    assetTag: v.string(),
    category: v.string(),
    status: v.string(),
    createdAt: v.number(),
    borrowerId: v.optional(v.id("borrowers")),
  }).index("by_assetTag", ["assetTag"]),
  borrowers: defineTable({
    fullName: v.string(),
    department: v.string(),
    createdAt: v.number(),
  }),
  assetLogs: defineTable({
    assetId: v.id("assets"),
    action: v.string(),
    borrowerId: v.optional(v.id("borrowers")),
    message: v.string(),
    createdAt: v.number(),
  }).index("by_assetId", ["assetId"]),
  hardwareInventory: defineTable({
    // Legacy fields kept temporarily for migration compatibility.
    assetTag: v.string(),
    brand: v.optional(v.string()),
    category: v.optional(v.string()),
    assignedTo: v.optional(v.string()),
    location: v.optional(v.string()),
    model: v.optional(v.string()),
    notes: v.optional(v.string()),
    dateAcquired: v.optional(v.number()),
    assetType: v.optional(v.string()),
    assetNameDescription: v.optional(v.string()),
    specifications: v.optional(v.string()),
    serialNumber: v.string(),
    locationPersonAssigned: v.optional(v.string()),
    department: v.optional(v.string()),
    status: v.string(),
    turnoverTo: v.optional(v.string()),
    borrower: v.optional(v.string()),
    // Legacy compatibility fields kept only for existing records.
    borrowerEmail: v.optional(v.string()),
    returnDueDate: v.optional(v.string()),
    registerMode: v.optional(v.string()),
    workstationType: v.optional(v.string()),
    specsTier: v.optional(v.string()),
    desktopMonitorAssetTag: v.optional(v.string()),
    desktopMonitorSlot: v.optional(v.string()),
    desktopMonitorSerialNumber: v.optional(v.string()),
    desktopMonitorSpecs: v.optional(v.string()),
    desktopMonitorConsumables: v.optional(v.string()),
    desktopSystemUnitAssetTag: v.optional(v.string()),
    desktopSystemUnitSpecs: v.optional(v.string()),
    desktopCaseBrand: v.optional(v.string()),
    desktopMouseAssetTag: v.optional(v.string()),
    desktopMouseSerialNumber: v.optional(v.string()),
    desktopMouseSpecs: v.optional(v.string()),
    desktopKeyboardAssetTag: v.optional(v.string()),
    desktopKeyboardSerialNumber: v.optional(v.string()),
    desktopKeyboardSpecs: v.optional(v.string()),
    desktopMonitorImageStorageId: v.optional(v.id("_storage")),
    desktopSystemUnitImageStorageId: v.optional(v.id("_storage")),
    desktopMouseImageStorageId: v.optional(v.id("_storage")),
    desktopKeyboardImageStorageId: v.optional(v.id("_storage")),
    workstationComponents: v.optional(
      v.array(
        v.object({
          assetTag: v.string(),
          componentType: v.string(),
          specifications: v.string(),
          imageStorageId: v.optional(v.id("_storage")),
        }),
      ),
    ),
    assignedDate: v.optional(v.string()),
    turnoverDate: v.optional(v.string()),
    purchaseDate: v.optional(v.string()),
    warranty: v.optional(v.string()),
    remarks: v.optional(v.string()),
    reservationBorrower: v.optional(v.string()),
    // Legacy compatibility fields kept only for existing records.
    reservationBorrowerEmail: v.optional(v.string()),
    reservationDepartment: v.optional(v.string()),
    reservationRequestedDate: v.optional(v.string()),
    reservationPickupDate: v.optional(v.string()),
    reservationReturnDueDate: v.optional(v.string()),
    reservationSlipNote: v.optional(v.string()),
    reservationLoggedAt: v.optional(v.number()),
    reservationStatus: v.optional(v.string()),
    borrowedAt: v.optional(v.number()),
    borrowReleaseCondition: v.optional(v.string()),
    borrowReleaseConditionCheckedAt: v.optional(v.number()),
    borrowReturnCondition: v.optional(v.string()),
    borrowReturnConditionCheckedAt: v.optional(v.number()),
    imageStorageId: v.optional(v.id("_storage")),
    imageStorageIds: v.optional(v.array(v.id("_storage"))),
    receivingFormStorageId: v.optional(v.id("_storage")),
    turnoverFormStorageId: v.optional(v.id("_storage")),
    droneFlightReportStorageId: v.optional(v.id("_storage")),
    droneMissingPartsNote: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_assetTag", ["assetTag"])
    .index("by_serialNumber", ["serialNumber"])
    .index("by_status", ["status"])
    .index("by_locationPersonAssigned", ["locationPersonAssigned"])
    .index("by_turnoverTo", ["turnoverTo"]),
  hardwareActivityEvents: defineTable({
    inventoryId: v.optional(v.id("hardwareInventory")),
    assetTag: v.string(),
    assetNameDescription: v.optional(v.string()),
    eventType: v.string(),
    message: v.string(),
    relatedPerson: v.optional(v.string()),
    location: v.optional(v.string()),
    status: v.optional(v.string()),
    actorName: v.optional(v.string()),
    createdAt: v.number(),
  }).index("by_createdAt", ["createdAt"]),
  monitoringSequences: defineTable({
    prefix: v.string(),
    year: v.number(),
    nextNumber: v.number(),
    updatedAt: v.number(),
  }).index("by_prefix_year", ["prefix", "year"]),
  monitoringTickets: defineTable({
    ticketNumber: v.string(),
    workType: v.string(),
    workflowType: v.string(),
    category: v.string(),
    status: v.string(),
    impact: v.optional(v.string()),
    urgency: v.optional(v.string()),
    priority: v.optional(v.string()),
    title: v.string(),
    requestDetails: v.string(),
    requestSnapshot: v.string(),
    requestSource: v.string(),
    requesterName: v.string(),
    requesterSection: v.optional(v.string()),
    requesterDepartment: v.optional(v.string()),
    requestReceivedAt: v.number(),
    assetId: v.optional(v.id("hardwareInventory")),
    assetTag: v.optional(v.string()),
    requiresPurchase: v.boolean(),
    requiresReplacement: v.boolean(),
    requiresSensitiveAccess: v.boolean(),
    approvalRequired: v.boolean(),
    approvalStage: v.string(),
    teamLeaderApprovalStatus: v.optional(v.string()),
    teamLeaderApprovalDate: v.optional(v.number()),
    teamLeaderApprovalReference: v.optional(v.string()),
    teamLeaderApprovalNote: v.optional(v.string()),
    osmdManagerApprovalStatus: v.optional(v.string()),
    osmdManagerApprovalDate: v.optional(v.number()),
    osmdManagerApprovalReference: v.optional(v.string()),
    osmdManagerApprovalNote: v.optional(v.string()),
    revisionReason: v.optional(v.string()),
    pendingReason: v.optional(v.string()),
    closeReason: v.optional(v.string()),
    majorIncident: v.boolean(),
    incidentReportRequired: v.boolean(),
    incidentReportAttached: v.boolean(),
    incidentReportStorageId: v.optional(v.id("_storage")),
    resolutionNote: v.optional(v.string()),
    fulfillmentNote: v.optional(v.string()),
    causeActionTaken: v.optional(v.string()),
    closureNote: v.optional(v.string()),
    attachments: v.array(
      v.object({
        kind: v.string(),
        label: v.string(),
        fileName: v.string(),
        contentType: v.optional(v.string()),
        storageId: v.id("_storage"),
        uploadedAt: v.number(),
        uploadedBy: v.string(),
      }),
    ),
    isp: v.optional(v.string()),
    connectionRole: v.optional(v.string()),
    outageArea: v.optional(v.string()),
    timeDetected: v.optional(v.number()),
    timeRestored: v.optional(v.number()),
    totalDowntimeMinutes: v.optional(v.number()),
    operationsBlocked: v.optional(v.boolean()),
    impactedUptime: v.optional(v.boolean()),
    meetingMode: v.optional(v.string()),
    meetingLocation: v.optional(v.string()),
    meetingStartAt: v.optional(v.number()),
    meetingEndAt: v.optional(v.number()),
    meetingAttendeeCount: v.optional(v.string()),
    meetingEquipmentSummary: v.optional(v.string()),
    meetingAssetItems: v.optional(
      v.array(
        v.object({
          assetId: v.id("hardwareInventory"),
          assetTag: v.string(),
          assetLabel: v.string(),
        }),
      ),
    ),
    requestedItemsText: v.optional(v.string()),
    requestedBorrowDate: v.optional(v.number()),
    expectedReturnAt: v.optional(v.number()),
    fleetDriverId: v.optional(v.id("fleetDrivers")),
    fleetDriverName: v.optional(v.string()),
    fleetDriverContactNumber: v.optional(v.string()),
    fleetVehicleId: v.optional(v.id("fleetVehicles")),
    fleetVehicleName: v.optional(v.string()),
    fleetVehiclePlateNumber: v.optional(v.string()),
    fleetVehicleType: v.optional(v.string()),
    fleetAssignedAt: v.optional(v.number()),
    fleetAssignedBy: v.optional(v.string()),
    // Travel Order: extended trip status (separate from generic system status)
    travelOrderStatus: v.optional(v.string()),
    // ETA & delay tracking
    estimatedArrivalTime: v.optional(v.number()),
    etaUpdatedAt: v.optional(v.number()),
    etaUpdatedBy: v.optional(v.string()),
    delayReason: v.optional(v.string()),
    // Cancellation
    cancellationReason: v.optional(v.string()),
    cancellationReasonDetail: v.optional(v.string()),
    cancelledBy: v.optional(v.string()),
    cancelledByRole: v.optional(v.string()),
    cancelledAt: v.optional(v.number()),
    // Travel return tracking
    travelReturnAt: v.optional(v.number()),
    travelReturnExtendedAt: v.optional(v.number()),
    // Multi-stop trip support
    tripMode: v.optional(v.string()),
    travelStops: v.optional(
      v.array(
        v.object({
          order: v.number(),
          type: v.string(),
          location: v.string(),
          scheduledTime: v.optional(v.number()),
          passengerNames: v.optional(v.array(v.string())),
        }),
      ),
    ),
    // Incident reporting
    incidentType: v.optional(v.string()),
    incidentDescription: v.optional(v.string()),
    incidentLocation: v.optional(v.string()),
    incidentReportedAt: v.optional(v.number()),
    incidentReportedBy: v.optional(v.string()),
    incidentResolvedAt: v.optional(v.number()),
    incidentResolvedBy: v.optional(v.string()),
    incidentResolutionNote: v.optional(v.string()),
    // Shared trip & billing
    sharedTripId: v.optional(v.string()),
    sharedTripRole: v.optional(v.string()),
    sharedTripLinkedTicketId: v.optional(v.id("monitoringTickets")),
    sharedTripCost: v.optional(v.number()),
    billingDepartment: v.optional(v.string()),
    billingCostCenter: v.optional(v.string()),
    // Odometer readings recorded at trip completion
    odometerStart: v.optional(v.number()),
    odometerEnd: v.optional(v.number()),
    odometerStartPhotoId: v.optional(v.id("_storage")),
    odometerEndPhotoId: v.optional(v.id("_storage")),
    // Conflict override
    conflictOverrideReason: v.optional(v.string()),
    conflictOverrideBy: v.optional(v.string()),
    notificationSeenByGroups: v.optional(v.array(v.string())),
    notificationSeenAt: v.optional(v.number()),
    notificationSeenBy: v.optional(v.string()),
    borrowingItems: v.optional(
      v.array(
        v.object({
          assetId: v.id("hardwareInventory"),
          assetTag: v.string(),
          assetLabel: v.string(),
          releaseCondition: v.string(),
          returnCondition: v.optional(v.string()),
          returnedAt: v.optional(v.number()),
        }),
      ),
    ),
    createdAt: v.number(),
    updatedAt: v.number(),
    createdBy: v.string(),
    updatedBy: v.string(),
    resolvedAt: v.optional(v.number()),
    fulfilledAt: v.optional(v.number()),
    closedAt: v.optional(v.number()),
  })
    .index("by_ticketNumber", ["ticketNumber"])
    .index("by_workflowType", ["workflowType"])
    .index("by_status", ["status"])
    .index("by_updatedAt", ["updatedAt"])
    .index("by_requestReceivedAt", ["requestReceivedAt"]),
  monitoringApprovalHistory: defineTable({
    ticketId: v.id("monitoringTickets"),
    approver: v.string(),
    decision: v.string(),
    reference: v.optional(v.string()),
    note: v.optional(v.string()),
    recordedBy: v.string(),
    createdAt: v.number(),
  })
    .index("by_ticketId", ["ticketId"])
    .index("by_createdAt", ["createdAt"]),
  officeCalendar: defineTable({
    holidayDate: v.string(),
    label: v.string(),
    scope: v.string(),
    active: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_holidayDate", ["holidayDate"])
    .index("by_active", ["active"]),
  dashboardCalendarEvents: defineTable({
    title: v.string(),
    requestedBy: v.optional(v.string()),
    assignedStaff: v.array(v.string()),
    neededItems: v.string(),
    location: v.optional(v.string()),
    notes: v.optional(v.string()),
    startAt: v.number(),
    endAt: v.optional(v.number()),
    createdAt: v.number(),
    updatedAt: v.number(),
    createdBy: v.optional(v.string()),
  })
    .index("by_startAt", ["startAt"])
    .index("by_updatedAt", ["updatedAt"]),
  fleetDrivers: defineTable({
    name: v.string(),
    position: v.optional(v.string()),
    contactNumber: v.optional(v.string()),
    status: v.string(),
    notes: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_status", ["status"])
    .index("by_updatedAt", ["updatedAt"]),
  fleetVehicles: defineTable({
    name: v.string(),
    plateNumber: v.string(),
    vehicleType: v.string(),
    capacity: v.optional(v.number()),
    status: v.string(),
    notes: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_status", ["status"])
    .index("by_updatedAt", ["updatedAt"]),
  operationsTasks: defineTable({
    title: v.string(),
    description: v.optional(v.string()),
    status: v.string(),
    priority: v.string(),
    owner: v.optional(v.string()),
    dueLabel: v.optional(v.string()),
    tags: v.array(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_status", ["status"])
    .index("by_updatedAt", ["updatedAt"]),
  officeSoftwareInventory: defineTable({
    softwareName: v.string(),
    vendor: v.optional(v.string()),
    version: v.optional(v.string()),
    licenseType: v.optional(v.string()),
    seatCount: v.optional(v.number()),
    assignedTo: v.optional(v.string()),
    department: v.optional(v.string()),
    purchaseDate: v.optional(v.string()),
    renewalDate: v.optional(v.string()),
    status: v.string(),
    notes: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_status", ["status"])
    .index("by_renewalDate", ["renewalDate"])
    .index("by_updatedAt", ["updatedAt"]),
  accessAccountsInventory: defineTable({
    systemName: v.string(),
    accountName: v.string(),
    accountType: v.optional(v.string()),
    ownerName: v.optional(v.string()),
    department: v.optional(v.string()),
    accessLevel: v.optional(v.string()),
    mfaEnabled: v.boolean(),
    lastReviewedDate: v.optional(v.string()),
    status: v.string(),
    vaultReference: v.optional(v.string()),
    notes: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_status", ["status"])
    .index("by_lastReviewedDate", ["lastReviewedDate"])
    .index("by_updatedAt", ["updatedAt"]),
  clearanceForms: defineTable({
    employeeId: v.id("users"),
    employeeName: v.string(),
    section: v.optional(v.string()),
    division: v.optional(v.string()),
    formDate: v.string(),
    accountsAccess: v.array(
      v.object({
        item: v.string(),
        label: v.string(),
        checked: v.boolean(),
        remarks: v.string(),
      }),
    ),
    itEquipment: v.array(
      v.object({
        item: v.string(),
        label: v.string(),
        checked: v.boolean(),
        remarks: v.string(),
      }),
    ),
    remarks: v.string(),
    recommendation: v.string(),
    checkedByName: v.optional(v.string()),
    checkedByRole: v.optional(v.string()),
    preApprovedByName: v.optional(v.string()),
    preApprovedByRole: v.optional(v.string()),
    approvedByName: v.optional(v.string()),
    approvedByRole: v.optional(v.string()),
    filledBy: v.string(),
    filledByUsername: v.string(),
    signedPdfStorageId: v.optional(v.id("_storage")),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_employeeId", ["employeeId"])
    .index("by_updatedAt", ["updatedAt"]),
  workflowRuns: defineTable({
    workflowId: v.string(),
    employeeId: v.id("users"),
    employeeName: v.string(),
    startedBy: v.string(),
    startedAt: v.number(),
    completedAt: v.number(),
    status: v.string(),
    completedStepIds: v.array(v.string()),
    skippedStepIds: v.array(v.string()),
  })
    .index("by_startedAt", ["startedAt"])
    .index("by_workflowId", ["workflowId"])
    .index("by_employeeId", ["employeeId"]),
  subscriptionsInventory: defineTable({
    serviceName: v.string(),
    vendor: v.optional(v.string()),
    planName: v.optional(v.string()),
    billingCycle: v.string(),
    cost: v.optional(v.number()),
    currency: v.string(),
    seatCount: v.optional(v.number()),
    ownerName: v.optional(v.string()),
    department: v.optional(v.string()),
    startDate: v.optional(v.string()),
    renewalDate: v.optional(v.string()),
    status: v.string(),
    notes: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_status", ["status"])
    .index("by_renewalDate", ["renewalDate"])
    .index("by_updatedAt", ["updatedAt"]),
  travelOrderNotifications: defineTable({
    ticketId: v.id("monitoringTickets"),
    ticketNumber: v.string(),
    recipientName: v.string(),
    recipientRole: v.string(),
    event: v.string(),
    message: v.string(),
    isRead: v.boolean(),
    deliveryStatus: v.string(),
    createdAt: v.number(),
    readAt: v.optional(v.number()),
  })
    .index("by_recipientName", ["recipientName"])
    .index("by_ticketId", ["ticketId"])
    .index("by_createdAt", ["createdAt"]),
  travelOrderActivityLog: defineTable({
    ticketId: v.id("monitoringTickets"),
    ticketNumber: v.string(),
    event: v.string(),
    description: v.string(),
    actorName: v.string(),
    actorRole: v.optional(v.string()),
    metadata: v.optional(v.string()),
    createdAt: v.number(),
  })
    .index("by_ticketId", ["ticketId"])
    .index("by_createdAt", ["createdAt"]),
});
