import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  assets: defineTable({
    assetTag: v.string(),
    category: v.string(),
    status: v.string(),
    createdAt: v.number(),
    borrowerId: v.optional(v.id("borrowers")),
  }).index("by_assetTag", ["assetTag"]),
  borrowers: defineTable({
    fullName: v.string(),
    department: v.string(),
    createdAt: v.number(),
  }),
  assetLogs: defineTable({
    assetId: v.id("assets"),
    action: v.string(),
    borrowerId: v.optional(v.id("borrowers")),
    message: v.string(),
    createdAt: v.number(),
  }).index("by_assetId", ["assetId"]),
  hardwareInventory: defineTable({
    // Legacy fields kept temporarily for migration compatibility.
    assetTag: v.string(),
    brand: v.optional(v.string()),
    category: v.optional(v.string()),
    assignedTo: v.optional(v.string()),
    location: v.optional(v.string()),
    model: v.optional(v.string()),
    notes: v.optional(v.string()),
    dateAcquired: v.optional(v.number()),
    assetType: v.optional(v.string()),
    assetNameDescription: v.optional(v.string()),
    specifications: v.optional(v.string()),
    serialNumber: v.string(),
    locationPersonAssigned: v.optional(v.string()),
    department: v.optional(v.string()),
    status: v.string(),
    turnoverTo: v.optional(v.string()),
    borrower: v.optional(v.string()),
    borrowerEmail: v.optional(v.string()),
    returnDueDate: v.optional(v.string()),
    returnReminderLastSentDate: v.optional(v.string()),
    registerMode: v.optional(v.string()),
    workstationType: v.optional(v.string()),
    specsTier: v.optional(v.string()),
    desktopMonitorAssetTag: v.optional(v.string()),
    desktopMonitorSlot: v.optional(v.string()),
    desktopMonitorSerialNumber: v.optional(v.string()),
    desktopMonitorSpecs: v.optional(v.string()),
    desktopMonitorConsumables: v.optional(v.string()),
    desktopSystemUnitAssetTag: v.optional(v.string()),
    desktopSystemUnitSpecs: v.optional(v.string()),
    desktopCaseBrand: v.optional(v.string()),
    desktopMouseAssetTag: v.optional(v.string()),
    desktopMouseSerialNumber: v.optional(v.string()),
    desktopMouseSpecs: v.optional(v.string()),
    desktopKeyboardAssetTag: v.optional(v.string()),
    desktopKeyboardSerialNumber: v.optional(v.string()),
    desktopKeyboardSpecs: v.optional(v.string()),
    workstationComponents: v.optional(
      v.array(
        v.object({
          assetTag: v.string(),
          componentType: v.string(),
          specifications: v.string(),
          imageStorageId: v.optional(v.id("_storage")),
        }),
      ),
    ),
    assignedDate: v.optional(v.string()),
    turnoverDate: v.optional(v.string()),
    purchaseDate: v.optional(v.string()),
    warranty: v.optional(v.string()),
    remarks: v.optional(v.string()),
    reservationBorrower: v.optional(v.string()),
    reservationBorrowerEmail: v.optional(v.string()),
    reservationDepartment: v.optional(v.string()),
    reservationRequestedDate: v.optional(v.string()),
    reservationPickupDate: v.optional(v.string()),
    reservationReturnDueDate: v.optional(v.string()),
    reservationSlipNote: v.optional(v.string()),
    reservationStatus: v.optional(v.string()),
    imageStorageId: v.optional(v.id("_storage")),
    receivingFormStorageId: v.optional(v.id("_storage")),
    turnoverFormStorageId: v.optional(v.id("_storage")),
    droneFlightReportStorageId: v.optional(v.id("_storage")),
    droneMissingPartsNote: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_assetTag", ["assetTag"])
    .index("by_serialNumber", ["serialNumber"])
    .index("by_status", ["status"])
    .index("by_locationPersonAssigned", ["locationPersonAssigned"])
    .index("by_turnoverTo", ["turnoverTo"]),
  hardwareActivityEvents: defineTable({
    inventoryId: v.optional(v.id("hardwareInventory")),
    assetTag: v.string(),
    assetNameDescription: v.optional(v.string()),
    eventType: v.string(),
    message: v.string(),
    relatedPerson: v.optional(v.string()),
    location: v.optional(v.string()),
    status: v.optional(v.string()),
    actorName: v.optional(v.string()),
    createdAt: v.number(),
  }).index("by_createdAt", ["createdAt"]),
});
