import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  assets: defineTable({
    assetTag: v.string(),
    category: v.string(),
    status: v.string(),
    createdAt: v.number(),
    borrowerId: v.optional(v.id("borrowers")),
  }).index("by_assetTag", ["assetTag"]),
  borrowers: defineTable({
    fullName: v.string(),
    department: v.string(),
    createdAt: v.number(),
  }),
  assetLogs: defineTable({
    assetId: v.id("assets"),
    action: v.string(),
    borrowerId: v.optional(v.id("borrowers")),
    message: v.string(),
    createdAt: v.number(),
  }).index("by_assetId", ["assetId"]),
  hardwareInventory: defineTable({
    // Legacy fields kept temporarily for migration compatibility.
    assetTag: v.string(),
    brand: v.optional(v.string()),
    category: v.optional(v.string()),
    assignedTo: v.optional(v.string()),
    location: v.optional(v.string()),
    model: v.optional(v.string()),
    notes: v.optional(v.string()),
    dateAcquired: v.optional(v.number()),
    assetType: v.optional(v.string()),
    assetNameDescription: v.optional(v.string()),
    specifications: v.optional(v.string()),
    serialNumber: v.string(),
    locationPersonAssigned: v.optional(v.string()),
    department: v.optional(v.string()),
    status: v.string(),
    turnoverTo: v.optional(v.string()),
    borrower: v.optional(v.string()),
    // Legacy compatibility fields kept only for existing records.
    borrowerEmail: v.optional(v.string()),
    returnDueDate: v.optional(v.string()),
    registerMode: v.optional(v.string()),
    workstationType: v.optional(v.string()),
    specsTier: v.optional(v.string()),
    desktopMonitorAssetTag: v.optional(v.string()),
    desktopMonitorSlot: v.optional(v.string()),
    desktopMonitorSerialNumber: v.optional(v.string()),
    desktopMonitorSpecs: v.optional(v.string()),
    desktopMonitorConsumables: v.optional(v.string()),
    desktopSystemUnitAssetTag: v.optional(v.string()),
    desktopSystemUnitSpecs: v.optional(v.string()),
    desktopCaseBrand: v.optional(v.string()),
    desktopMouseAssetTag: v.optional(v.string()),
    desktopMouseSerialNumber: v.optional(v.string()),
    desktopMouseSpecs: v.optional(v.string()),
    desktopKeyboardAssetTag: v.optional(v.string()),
    desktopKeyboardSerialNumber: v.optional(v.string()),
    desktopKeyboardSpecs: v.optional(v.string()),
    workstationComponents: v.optional(
      v.array(
        v.object({
          assetTag: v.string(),
          componentType: v.string(),
          specifications: v.string(),
          imageStorageId: v.optional(v.id("_storage")),
        }),
      ),
    ),
    assignedDate: v.optional(v.string()),
    turnoverDate: v.optional(v.string()),
    purchaseDate: v.optional(v.string()),
    warranty: v.optional(v.string()),
    remarks: v.optional(v.string()),
    reservationBorrower: v.optional(v.string()),
    // Legacy compatibility fields kept only for existing records.
    reservationBorrowerEmail: v.optional(v.string()),
    reservationDepartment: v.optional(v.string()),
    reservationRequestedDate: v.optional(v.string()),
    reservationPickupDate: v.optional(v.string()),
    reservationReturnDueDate: v.optional(v.string()),
    reservationSlipNote: v.optional(v.string()),
    reservationLoggedAt: v.optional(v.number()),
    reservationStatus: v.optional(v.string()),
    borrowedAt: v.optional(v.number()),
    borrowReleaseCondition: v.optional(v.string()),
    borrowReleaseConditionCheckedAt: v.optional(v.number()),
    borrowReturnCondition: v.optional(v.string()),
    borrowReturnConditionCheckedAt: v.optional(v.number()),
    imageStorageId: v.optional(v.id("_storage")),
    receivingFormStorageId: v.optional(v.id("_storage")),
    turnoverFormStorageId: v.optional(v.id("_storage")),
    droneFlightReportStorageId: v.optional(v.id("_storage")),
    droneMissingPartsNote: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_assetTag", ["assetTag"])
    .index("by_serialNumber", ["serialNumber"])
    .index("by_status", ["status"])
    .index("by_locationPersonAssigned", ["locationPersonAssigned"])
    .index("by_turnoverTo", ["turnoverTo"]),
  hardwareActivityEvents: defineTable({
    inventoryId: v.optional(v.id("hardwareInventory")),
    assetTag: v.string(),
    assetNameDescription: v.optional(v.string()),
    eventType: v.string(),
    message: v.string(),
    relatedPerson: v.optional(v.string()),
    location: v.optional(v.string()),
    status: v.optional(v.string()),
    actorName: v.optional(v.string()),
    createdAt: v.number(),
  }).index("by_createdAt", ["createdAt"]),
  monitoringSequences: defineTable({
    prefix: v.string(),
    year: v.number(),
    nextNumber: v.number(),
    updatedAt: v.number(),
  }).index("by_prefix_year", ["prefix", "year"]),
  monitoringTickets: defineTable({
    ticketNumber: v.string(),
    workType: v.string(),
    workflowType: v.string(),
    category: v.string(),
    status: v.string(),
    impact: v.optional(v.string()),
    urgency: v.optional(v.string()),
    priority: v.optional(v.string()),
    title: v.string(),
    requestDetails: v.string(),
    requestSnapshot: v.string(),
    requestSource: v.string(),
    requesterName: v.string(),
    requesterSection: v.optional(v.string()),
    requesterDepartment: v.optional(v.string()),
    requestReceivedAt: v.number(),
    assetId: v.optional(v.id("hardwareInventory")),
    assetTag: v.optional(v.string()),
    requiresPurchase: v.boolean(),
    requiresReplacement: v.boolean(),
    requiresSensitiveAccess: v.boolean(),
    approvalRequired: v.boolean(),
    approvalStage: v.string(),
    teamLeaderApprovalStatus: v.optional(v.string()),
    teamLeaderApprovalDate: v.optional(v.number()),
    teamLeaderApprovalReference: v.optional(v.string()),
    teamLeaderApprovalNote: v.optional(v.string()),
    osmdManagerApprovalStatus: v.optional(v.string()),
    osmdManagerApprovalDate: v.optional(v.number()),
    osmdManagerApprovalReference: v.optional(v.string()),
    osmdManagerApprovalNote: v.optional(v.string()),
    revisionReason: v.optional(v.string()),
    pendingReason: v.optional(v.string()),
    closeReason: v.optional(v.string()),
    majorIncident: v.boolean(),
    incidentReportRequired: v.boolean(),
    incidentReportAttached: v.boolean(),
    incidentReportStorageId: v.optional(v.id("_storage")),
    resolutionNote: v.optional(v.string()),
    fulfillmentNote: v.optional(v.string()),
    causeActionTaken: v.optional(v.string()),
    closureNote: v.optional(v.string()),
    attachments: v.array(
      v.object({
        kind: v.string(),
        label: v.string(),
        fileName: v.string(),
        contentType: v.optional(v.string()),
        storageId: v.id("_storage"),
        uploadedAt: v.number(),
        uploadedBy: v.string(),
      }),
    ),
    isp: v.optional(v.string()),
    connectionRole: v.optional(v.string()),
    outageArea: v.optional(v.string()),
    timeDetected: v.optional(v.number()),
    timeRestored: v.optional(v.number()),
    totalDowntimeMinutes: v.optional(v.number()),
    operationsBlocked: v.optional(v.boolean()),
    impactedUptime: v.optional(v.boolean()),
    meetingMode: v.optional(v.string()),
    meetingLocation: v.optional(v.string()),
    meetingStartAt: v.optional(v.number()),
    meetingEndAt: v.optional(v.number()),
    meetingAttendeeCount: v.optional(v.string()),
    meetingEquipmentSummary: v.optional(v.string()),
    meetingAssetItems: v.optional(
      v.array(
        v.object({
          assetId: v.id("hardwareInventory"),
          assetTag: v.string(),
          assetLabel: v.string(),
        }),
      ),
    ),
    expectedReturnAt: v.optional(v.number()),
    borrowingItems: v.optional(
      v.array(
        v.object({
          assetId: v.id("hardwareInventory"),
          assetTag: v.string(),
          assetLabel: v.string(),
          releaseCondition: v.string(),
          returnCondition: v.optional(v.string()),
          returnedAt: v.optional(v.number()),
        }),
      ),
    ),
    createdAt: v.number(),
    updatedAt: v.number(),
    createdBy: v.string(),
    updatedBy: v.string(),
    resolvedAt: v.optional(v.number()),
    fulfilledAt: v.optional(v.number()),
    closedAt: v.optional(v.number()),
  })
    .index("by_ticketNumber", ["ticketNumber"])
    .index("by_workflowType", ["workflowType"])
    .index("by_status", ["status"])
    .index("by_updatedAt", ["updatedAt"])
    .index("by_requestReceivedAt", ["requestReceivedAt"]),
  monitoringApprovalHistory: defineTable({
    ticketId: v.id("monitoringTickets"),
    approver: v.string(),
    decision: v.string(),
    reference: v.optional(v.string()),
    note: v.optional(v.string()),
    recordedBy: v.string(),
    createdAt: v.number(),
  })
    .index("by_ticketId", ["ticketId"])
    .index("by_createdAt", ["createdAt"]),
  officeCalendar: defineTable({
    holidayDate: v.string(),
    label: v.string(),
    scope: v.string(),
    active: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_holidayDate", ["holidayDate"])
    .index("by_active", ["active"]),
  dashboardCalendarEvents: defineTable({
    title: v.string(),
    requestedBy: v.optional(v.string()),
    assignedStaff: v.array(v.string()),
    neededItems: v.string(),
    location: v.optional(v.string()),
    notes: v.optional(v.string()),
    startAt: v.number(),
    endAt: v.optional(v.number()),
    createdAt: v.number(),
    updatedAt: v.number(),
    createdBy: v.optional(v.string()),
  })
    .index("by_startAt", ["startAt"])
    .index("by_updatedAt", ["updatedAt"]),
  operationsTasks: defineTable({
    title: v.string(),
    description: v.optional(v.string()),
    status: v.string(),
    priority: v.string(),
    owner: v.optional(v.string()),
    dueLabel: v.optional(v.string()),
    tags: v.array(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_status", ["status"])
    .index("by_updatedAt", ["updatedAt"]),
});
