export const REQUEST_TYPES = [
  {
    id: "equipment_borrower",
    label: "IT Equipment Borrower",
    description: "Borrow available IT equipment from storage.",
    href: "/requests/new/equipment-borrower",
    enabled: true,
    examples: ["Laptop", "Monitor", "Accessories"],
  },
  {
    id: "drone_borrower",
    label: "Drone Borrower",
    description: "Borrow an available drone kit for field work.",
    href: "/requests/new/drone-borrower",
    enabled: true,
    examples: ["Drone kit", "Field work", "Flight activity"],
  },
  {
    id: "it_incident",
    label: "IT Support",
    description: "Something is broken, blocked, or not working normally.",
    href: "/requests/new/it-support",
    enabled: true,
    examples: ["Forgot password", "Cannot log in", "System error"],
  },
  {
    id: "it_request",
    label: "IT Request",
    description: "Ask IT to create, change, retrieve, grant, or set up something.",
    href: "/requests/new/it-request",
    enabled: true,
    examples: ["System access", "Data or recording", "Software setup"],
  },
  {
    id: "meeting_request",
    label: "Meeting Request",
    description: "Request meeting support, room setup, or equipment.",
    enabled: false,
    examples: ["Room setup", "Meeting equipment", "Hybrid support"],
  },
  {
    id: "it_exemption",
    label: "IT Exemption Form",
    description: "Request an exception from a normal IT rule or process.",
    enabled: false,
    examples: ["Policy exception", "Temporary approval", "Special case"],
  },
] as const;
